package com.alzpal.dashboardactivity.tracker;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity
public class UserDetails {

    // The unique ID for each user detail entry. This is automatically generated by the Room database.
    @PrimaryKey(autoGenerate = true)
    private int id;

    // The name of the user.
    private String name;

    // The age of the user.
    private String age;

    // The phone number of the user.
    private String number;

    /**
     * Constructor to create a UserDetails object.
     *
     * @param name   The name of the user.
     * @param age    The age of the user.
     * @param number The phone number of the user.
     */
    public UserDetails(String name, String age, String number) {
        this.name = name;
        this.age = age;
        this.number = number;
    }

    // Getter for the ID. This is used to uniquely identify each record in the database.
    public int getId() {
        return id;
    }

    // Setter for the ID. This is used to set the unique ID for a record, typically done by Room database.
    public void setId(int id) {
        this.id = id;
    }

    // Getter for the name of the user.
    public String getName() {
        return name;
    }

    // Setter for the name of the user.
    public void setName(String name) {
        this.name = name;
    }

    // Getter for the age of the user.
    public String getAge() {
        return age;
    }

    // Setter for the age of the user.
    public void setAge(String age) {
        this.age = age;
    }

    // Getter for the phone number of the user.
    public String getNumber() {
        return number;
    }

    // Setter for the phone number of the user.
    public void setNumber(String number) {
        this.number = number;
    }
}
